Kyle's Doxygen Test: Dog Class Reference
Dog Class Reference
Represents a dog.
#include <dog.hpp>
Public Member Functions
Dog (const char *_name)
Creates a new Dog.
void bark (void)
Causes the dog to bark.
void run (int minutes)
Causes the dog to run.
void sleep (int minutes)
Causes the dog to sleep.
Protected Member Functions
bool checkEnergy (int energyToExpend)
Checks the dog's energy.
Private Attributes
const char * name
The dog's name.
int energy
The dog's available energy.
Detailed Description
Represents a dog.
This class keeps track of the dog's energy level, and performs actions for the dog based on how much energy it has. Sleeping regains energy for the dog, while barking and running use energy up.
Definition at line 13 of file dog.hpp.
Constructor & Destructor Documentation
Dog()
Dog::Dog (const char * _name)
Creates a new Dog.
Creates a new Dog named _name with half of its maximum energy.
Parameters
_name The dog's name.
Definition at line 5 of file dog.cpp.
                           : name(_name) {
     energy = MAX_ENERGY / 2;
     printf("Created %s the dog.\n", name);
 }
References energy, MAX_ENERGY, and name.
Member Function Documentation
bark()
void Dog::bark (void)
Causes the dog to bark.
Causes the dog to bark if it has enough energy to do so. Barking costs 1 energy to do. If the dog does not have enough energy, then the bark fails.
Definition at line 10 of file dog.cpp.
                    {
     int energyToExpend = 1;
     if (checkEnergy(energyToExpend)) {
         energy -= energyToExpend;
         printf("%s BARKS!\n", name);
     } else {
         fprintf(stderr, "%s is too tired to bark.\n", name);
     }
 }
References checkEnergy(), energy, and name.
Referenced by testDog().
checkEnergy()
bool Dog::checkEnergy (int energyToExpend) protected
Checks the dog's energy.
Compares an amount of energy with the dog's current available energy. This function can be used to determine if the dog is able to take an action that costs energy.
Parameters
energyToExpend An amount of energy to check.
Returns
True if the dog has enough energy, and false otherwise.
Definition at line 50 of file dog.cpp.
{
     if (energy > energyToExpend) {
         return true;
     }
     return false;
 }
References energy.
Referenced by bark(), and run().
run()
void Dog::run (int minutes)
Causes the dog to run.
Causes the dog to run for an amount of time if it has enough energy to run for that long. If the dog does not have enough energy, then the run fails. If the dog cannot complete the full run, no running takes place and no energy is expended. Running costs 3 energy per minute.
Parameters
minutes Number of minutes for the dog to run.
Definition at line 20 of file dog.cpp.
{
     int energyToExpend = multiply(minutes, 3);
     if (checkEnergy(energyToExpend)) {
         energy -= energyToExpend;
         printf("%s runs for %d minute%s.\n",
                name,
                minutes,
                minutes == 1 ? "" : "s");
     } else {
         fprintf(stderr,
                 "%s is too tired to run for %d minute%s.\n",
                 name,
                 minutes,
                 minutes == 1 ? "" : "s");
     }
 }
References checkEnergy(), energy, multiply(), and name.
Referenced by testDog().
sleep()
void Dog::sleep (int minutes)
Causes the dog to sleep.
Sleeping replenishes the dog's energy. The dog regains an amount of energy equal to twice the number of minutes slept. The dog will always sleep, regardless of how much energy it has remaining.
Parameters
minutes Number of minutes for the dog to sleep.
Definition at line 37 of file dog.cpp.
{
     int energyToRegain = multiply(minutes, 2);
     energy += energyToRegain;
     printf("%s sleeps for %d minute%s.\n",
            name,
            minutes,
            minutes == 1 ? "" : "s");
     if (energy > MAX_ENERGY) {
         energy = MAX_ENERGY;
         printf("%s is fully rested.\n", name);
     }
 }
References energy, MAX_ENERGY, multiply(), and name.
Referenced by testDog().
Member Data Documentation
energy
int Dog::energy private
The dog's available energy.
Represents the amount of energy the dog has available. This is set in the constructor and should not be accessed externally. Taking actions that cost the dog energy will cause this value to drop, and sleeping will cause this value to rise.
Definition at line 89 of file dog.hpp.
Referenced by bark(), checkEnergy(), Dog(), run(), and sleep().
name
const char* Dog::name private
The dog's name.
Represents the dog's name. This is set when the dog is created, and cannot be changed afterwards.
Definition at line 79 of file dog.hpp.
Referenced by bark(), Dog(), run(), and sleep().
The documentation for this class was generated from the following files:
src/dog.hpp
src/dog.cpp