Kyle's Doxygen Test: test/src/tmp_test.cpp File Reference
tmp_test.cpp File Reference
#include "project/tmp.hpp"
#include <gtest/gtest.h>
Functions
TEST (TmpAddTest, CheckValues)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 11 of file tmp_test.cpp.
 {
   ::testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
 }
References testDog(), and testNumbers().
TEST()
TEST (TmpAddTest , CheckValues)
Definition at line 5 of file tmp_test.cpp.
 {
   ASSERT_EQ(tmp::add(1, 2), 3);
   EXPECT_TRUE(true);
 }
References add().